import type { Metadata } from 'next';
import Navbar from './components/Navbar';
import './assets/css/globals.css';
import Footer from './components/Footer';

export const metadata: Metadata = {
  title: 'Frontend Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
